name: 游닂 Sugest칚o de Novo M칩dulo
description: Proponha um novo m칩dulo ou tema para ser inclu칤do na trilha de certifica칞칚o do QATS. A proposta deve estar alinhada aos objetivos e  estrutura das trilhas j치 definidas no projeto.
title: "游닂 [Sugest칚o de M칩dulo] T칤tulo do m칩dulo sugerido"
labels: [sugestao, modulo, comunidade]
body:
  - type: input
    id: titulo
    attributes:
      label: T칤tulo do M칩dulo
      placeholder: "Ex: Testes de Performance com JMeter"
    validations:
      required: true

  - type: textarea
    id: resumo
    attributes:
      label: Resumo da Proposta
      description: Descreva em poucas linhas o que este m칩dulo abordaria e explique como ele se encaixa na trilha existente ou se cria uma nova.
      placeholder: "Este m칩dulo tem como objetivo introduzir conceitos b치sicos de performance testing utilizando a ferramenta JMeter..."
    validations:
      required: true

  - type: textarea
    id: objetivos
    attributes:
      label: Objetivos de Aprendizagem
      description: Liste os principais objetivos que o aluno deve alcan칞ar. Os objetivos devem ser claros, mensur치veis e relacionados a compet칡ncias espec칤ficas do QA.
      placeholder: |
        - Entender o que s칚o testes de performance
        - Configurar e executar cen치rios simples no JMeter
        - Interpretar os principais relat칩rios de execu칞칚o
    validations:
      required: false

  - type: textarea
    id: referencias
    attributes:
      label: Fontes e Refer칡ncias
      description: Cite materiais de apoio, livros, artigos, v칤deos, etc. Priorize refer칡ncias de fontes abertas ou com licen칞a compat칤vel com CC BY-SA 4.0.
      placeholder: "- Livro XYZ - Cap칤tulo 3\n- Documenta칞칚o do JMeter\n- Curso do Ministry of Testing"
    validations:
      required: false

  - type: dropdown
    id: nivel
    attributes:
      label: N칤vel sugerido
      options:
        - Todos os n칤veis
        - Iniciante
        - Intermedi치rio
        - Avan칞ado
    validations:
      required: true
